config/routes.rb
Xlogger::Application.routes.draw do |map|
  # map.connect ':controller/:action/:id'
  # params = { :controller => 'blog',
  #            :action => 'edit', 
  #            :id    =>  '22'
  #            }

  # sets up a default map
  #map.connect ':controller/:action/:id', :controller => 'pages'
  resources :workouts
  resources :warmups
  resources :templates
  resources :exercises
  resources :entries
  resources :users
  resources :events
  resources :sessions, :only => [:new, :create, :destroy]

  get "calendar/index"
  get "templates/index"  ### < maybe

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  map.signup 'signup', :controller => 'users', :action => 'new'
  map.signin 'signin', :controller => 'sessions', :action => 'new'
  map.signout 'signout', :controller => 'sessions', :action => 'destroy'

  map.contact 'contact', :controller => 'pages', :action => 'contact'
  map.about 'about', :controller => 'pages', :action => 'about'
  map.help 'help', :controller => 'pages', :action => 'help'

  map.calendar 'calendar', :controller => 'calendar', :action => 'index'

  map.root :controller => 'pages', :action => 'home'
end  

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many   :exercises, :as => :exerciseable, :dependent => :destroy
  accepts_nested_attributes_for :exercises
  belongs_to :event
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  # GET /workouts
  # GET /workouts.xml
  def index
    @workouts = Workout.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @workouts }
    end
  end

  # GET /workouts/1
  # GET /workouts/1.xml
  def show
    @workout = Workout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @workout }
    end
  end

  # GET /workouts/new
  # GET /workouts/new.xml
  def new
    @workout = Workout.new
    # fetches all the crossfit templates ordered by name
    #@templates = Template.where(:user_id => 
    #  User.find_by_name("crossfit").id).order(:name)
	  @templates = Template.where(:user_id => current_user.id).order(:name) 
    @workout.event_id = params[:event_id]

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @workout }
    end
  end

  # GET /workouts/1/edit
  def edit
    @workout = Workout.find(params[:id])
  end

  # POST /workouts
  # POST /workouts.xml
  def create
    @workout = Workout.new(params[:workout])
    if @workout.template_id != nil
      @template = Template.find(@workout.template_id)
      if @template.name != "Custom"
        @workout.attributes = { :name => @template.name, 
          :description => @template.description }
        @workout.save
        @exercises = @template.exercises
        @exercises.each do |exercise|
          @temp = @workout.exercises.create(:name => exercise.name,
                                    :reps => exercise.reps,
                                    :weight => exercise.weight )
          @temp.save
        end
      end
    end
    respond_to do |format|
      if @workout.save
        format.html { redirect_to(edit_workout_path(@workout), :notice => 'Workout was successfully created.') }
        format.xml  { render :xml => @workout, :status => :created, :location => @workout }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @workout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /workouts/1
  # PUT /workouts/1.xml
  def update
    @workout = Workout.find(params[:id])

    respond_to do |format|
      if @workout.update_attributes(params[:workout])
        format.html { redirect_to(@workout, :notice => 'Workout was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @workout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.xml
  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to(workouts_url) }
      format.xml  { head :ok }
    end
  end

  
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>
<%= nested_form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.fields_for :exercises do |exercise_form| %>
    <%= exercise_form.label :name, "Exercise" %><br />
    <%= exercise_form.text_field :name %><br />
    <%= exercise_form.label :reps %><br />
    <%= exercise_form.text_field :reps %><br />
    <%= exercise_form.label :weight %><br />
    <%= exercise_form.text_field :weight %><br /
    <%= exercise_form.link_to_remove "Remove this exercise" %>
  <% end %>
  <%= f.link_to_add "Add an exercise", :exercises %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>Listing workouts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Entry</th>
    <th>Template</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workouts.each do |workout| %>
  <tr>
    <td><%= workout.name %></td>
    <td><%= workout.description %></td>
    <td><%= workout.entry_id %></td>
    <td><%= workout.template_id %></td>
    <td><%= link_to 'Show', workout %></td>
    <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
    <td><%= link_to 'Destroy', workout, :confirm => 'Are you sure?', :controller => "workout", :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New event</h1>

<%= nested_form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Load from template" %><br />
    <%= f.collection_select :template_id, @templates, :id, :name %>
    <!--%= f.text_field :template_id %-->
  </div>

  <div class="field">
    <%= f.hidden_field :event_id %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<%= link_to 'Back', calendar_index_path %>
<%= link_to 'Workout Data', new_entry_path(:user_id => @current_user.id) %>

app/views/workouts/show.html.erb
<p>
  <b>Name:</b>
  <%= @workout.name %>
</p>

<p>
  <b>Comments:</b>
  <%= @workout.description %>
</p>


<% @exercises = @workout.exercises %>
<% @exercises.each do |exercise| %>
  <p>
    <% unless exercise.name==""  %>
    <%= "Exercise:   " %>
      <%= exercise.name %><br />
      <% unless exercise.reps=="" %>
        <%= "Reps:  " %>
        <%= exercise.reps %><br />
      <% end %>
      <% unless exercise.weight=="" %>
        <%= "Weight:  "  %>
        <%= exercise.weight %><br />
      <% end %>
    <% end %>
  </p>
<% end %>

<%= link_to 'Edit', edit_workout_path(@workout) %>