config/routes.rb
Xlogger::Application.routes.draw do |map|
  # map.connect ':controller/:action/:id'
  # params = { :controller => 'blog',
  #            :action => 'edit', 
  #            :id    =>  '22'
  #            }

  # sets up a default map
  #map.connect ':controller/:action/:id', :controller => 'pages'
  resources :workouts
  resources :warmups
  resources :templates
  resources :exercises
  resources :entries
  resources :users
  resources :events
  resources :sessions, :only => [:new, :create, :destroy]

  get "calendar/index"
  get "templates/index"  ### < maybe

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  map.signup 'signup', :controller => 'users', :action => 'new'
  map.signin 'signin', :controller => 'sessions', :action => 'new'
  map.signout 'signout', :controller => 'sessions', :action => 'destroy'

  map.contact 'contact', :controller => 'pages', :action => 'contact'
  map.about 'about', :controller => 'pages', :action => 'about'
  map.help 'help', :controller => 'pages', :action => 'help'

  map.calendar 'calendar', :controller => 'calendar', :action => 'index'

  map.root :controller => 'pages', :action => 'home'
end  

app/views/templates/_form.html.erb
<%= nested_form_for @template do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :exercises do |exercise_form| %>
    <%= exercise_form.label :name, "Exercise" %><br />
    <%= exercise_form.text_field :name %><br />
    <%= exercise_form.label :reps %><br />
    <%= exercise_form.text_field :reps %><br />
    <%= exercise_form.label :weight %><br />
    <%= exercise_form.text_field :weight %><br /
    <%= exercise_form.link_to_remove "Remove this exercise" %>
  <% end %>
  <%= f.link_to_add "Add an exercise", :exercises %>



  <div class="field">
    <%= f.label :description, "Comments" %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= button_to 'Destroy', @template, :confirm => 'Are you sure?', :controller => "template", :method => :delete %>
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.name %></td>
    <td><%= template.description %></td>
    <td><%= link_to 'View', template_path(template) %></td>
    <td><%= link_to 'Edit', edit_template_path(template) %></td>
    <!--td><%= link_to 'Destroy', template, :confirm => 'Are you sure?', :controller => "template", :method => :delete %></td-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Named Workout', new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @template.name %>
</p>

<p>
  <b>Comments:</b>
  <%= @template.description %>
</p>


<p>
<% @exercises = @template.exercises %>
<% @exercises.each do |exercise| %>
  <p><%= "Exercise:   " %>
     <%= exercise.name %><br />
     <%= "Reps:  " %>
     <%= exercise.reps %><br />
     <%= "Weight:  "  %>
     <%= exercise.weight %><br />
  </p>
<% end %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %>