config/routes.rb
Xlogger::Application.routes.draw do |map|
  # map.connect ':controller/:action/:id'
  # params = { :controller => 'blog',
  #            :action => 'edit', 
  #            :id    =>  '22'
  #            }

  # sets up a default map
  #map.connect ':controller/:action/:id', :controller => 'pages'
  resources :workouts
  resources :warmups
  resources :templates
  resources :exercises
  resources :entries
  resources :users
  resources :events
  resources :sessions, :only => [:new, :create, :destroy]

  get "calendar/index"
  get "templates/index"  ### < maybe

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  map.signup 'signup', :controller => 'users', :action => 'new'
  map.signin 'signin', :controller => 'sessions', :action => 'new'
  map.signout 'signout', :controller => 'sessions', :action => 'destroy'

  map.contact 'contact', :controller => 'pages', :action => 'contact'
  map.about 'about', :controller => 'pages', :action => 'about'
  map.help 'help', :controller => 'pages', :action => 'help'

  map.calendar 'calendar', :controller => 'calendar', :action => 'index'

  map.root :controller => 'pages', :action => 'home'
end  

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user

  scope :before, lambda {|end_time| {:conditions => ["ends_at < ?", Event.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Event.format_date(start_time)] }}
  
  has_many :workouts, :dependent => :destroy
  accepts_nested_attributes_for :workouts, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  
  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => self.all_day,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
    
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index   
    @events = Event.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.js  { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    @workout = Workout.where (:event_id => @event.id ).first


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
      format.js { render :json => @event.to_json }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new
    @event.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])
    @event.user_id = current_user.id   
    @start_date = @event.starts_at
    @start_date = DateTime.civil(@start_date.year, @start_date.month, @start_date.day + 1, 1, 1, 1)
    @end_date = DateTime.civil(@start_date.year, @start_date.month, @start_date.day, 1, 1, 2)
    @event.ends_at = @end_date
    @event.all_day = true
    respond_to do |format|
      if @event.save
        format.html { redirect_to(new_workout_path(:user_id => @current_user.id, :event_id => @event.id ), :notice => 'Pick the workout template.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  # PUT /events/1.js
  # when we drag an event on the calendar (from day to day on the month view, or stretching
  # it on the week or day view), this method will be called to update the values.
  # viv la REST!
  def update
    @event = Event.find(params[:id])
    
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to( edit_workout_path(@workout) ) }
        format.xml  { head :ok }
        format.js { head :ok}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
        format.js  { render :js => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(calendar_index_path) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :default => 'Workout' %>
  </div>  

  
  <div class="field">
    <%= f.label :starts_at %><br />
    <!--%= f.datetime_select :starts_at %-->
    <%= f.text_field :starts_at %><br />
  </div>
  <div class="field">   
    <!--%= f.hidden_field :ends_at, :default => 1.minutes.from_now %-->
  </div>
  <div class="field">   
    <%= f.hidden_field :all_day, :default => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', calendar_index_path %>
<%= button_to 'Remove', @event, :confirm => 'Are you sure?', :method => :delete %> |

app/views/events/index.html.erb
<h1>Listing events</h1>

<script type="text/javascript" charset="utf-8">
  $(function() {
    new Highcharts.Chart({
      chart: {
        renderTo: "events_chart"
      },
      title: {
        text: "Weight over time"
      },
      xAxis: {
        type: "datetime"
      },
      yAxis: {
        title: {
          text: "Weight"
        }
      },
      series: [{
        pointInterval: <%= 1.day * 1000 %>,
        pointStart: <%= 3.weeks.ago.to_i * 1000 %>,
        data: [1, 2, 5, 7, 3]
      }]
    });
  });
</script>
<div id="events_chart" style="width:560px; height:300px"></div>

<table>
  <tr>
    <th>Title</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>All day</th>
    <th>Description</th>
    <th>User_id</th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.starts_at %></td>
    <td><%= event.ends_at %></td>
    <td><%= event.all_day %></td>
    <td><%= event.description %></td>
    <td><%= event.user_id %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :controller => "event", :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'view calendar', calendar_index_path %>
<br/>
<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', calendar_index_path %>
<%= link_to 'Workout Data', new_entry_path(:user_id => @current_user.id) %>

app/views/events/show.html.erb
<head>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
</head>
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Starts at:</b>
  <%= @event.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @event.ends_at %>
</p>

<p>
  <b>All day:</b>
  <%= @event.all_day %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Workout:</b>
  <%= @workout.name %>
</p>


<% @workout.exercises.each do |exercise| %>
  <p><%= exercise.name %><br />
     <%= exercise.reps %><br />
     <%= exercise.weight %><br />
  </p>
<% end %>



<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', calendar_index_path %>