config/routes.rb
Xlogger::Application.routes.draw do |map|
  # map.connect ':controller/:action/:id'
  # params = { :controller => 'blog',
  #            :action => 'edit', 
  #            :id    =>  '22'
  #            }

  # sets up a default map
  #map.connect ':controller/:action/:id', :controller => 'pages'
  resources :workouts
  resources :warmups
  resources :templates
  resources :exercises
  resources :entries
  resources :users
  resources :events
  resources :sessions, :only => [:new, :create, :destroy]

  get "calendar/index"
  get "templates/index"  ### < maybe

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  map.signup 'signup', :controller => 'users', :action => 'new'
  map.signin 'signin', :controller => 'sessions', :action => 'new'
  map.signout 'signout', :controller => 'sessions', :action => 'destroy'

  map.contact 'contact', :controller => 'pages', :action => 'contact'
  map.about 'about', :controller => 'pages', :action => 'about'
  map.help 'help', :controller => 'pages', :action => 'help'

  map.calendar 'calendar', :controller => 'calendar', :action => 'index'

  map.root :controller => 'pages', :action => 'home'
end  

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<script type="text/javascript"> 

</script>
  <img src="/images/logo.png" name="menu" width="300" height="233" border="0">
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Calendar", calendar_index_path %></li>
      <li><%= link_to "Named Workouts", templates_path %></li>
      <li><%= link_to "Account Management", edit_user_path(current_user) %></li>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html>
<head>
  <title>Xlogger</title>
  <%= stylesheet_link_tag "fullcalendar.css" %>
  <%= stylesheet_link_tag "application.css" %>
  <%= stylesheet_link_tag "jquery-ui-1.8.13.custom.css" %>
  <%= javascript_include_tag "jquery.js" %>
  <%= javascript_include_tag 'jquery', 'nested_form' %>
  <%= javascript_include_tag "jquery.rest.js" %>
  <%= javascript_include_tag "rails.js" %>
  <%= javascript_include_tag "application_jquery.js" %>
  <%= javascript_include_tag "highcharts.js" %>
  
  <!-- these are needed for the calendar. -->
  <%= javascript_include_tag "jquery-ui-1.8.11.custom.min.js" %>
  <%= javascript_include_tag "fullcalendar.js" %>
  <%= javascript_include_tag "calendar.js" %>
  
  <!-- dont include 1.5.1 it breaks calendar-->
  <!--%= javascript_include_tag "jquery-1.5.1.min.js"%-->
  <%= javascript_include_tag "jquery-ui-1.8.13.custom.min.js"%>

  
  <%= csrf_meta_tag %>  
  
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
  
  <%= render 'layouts/stylesheets' %>
  
  <script type="text/javascript">
			$(function(){

				// Accordion
				$("#accordion").accordion({ header: "h3" });
	
				// Tabs
				$('#tabs').tabs();
	

				// Dialog			
				$('#dialog').dialog({
					autoOpen: false,
					width: 600,
					buttons: {
						"Ok": function() { 
							$(this).dialog("close"); 
						}, 
						"Cancel": function() { 
							$(this).dialog("close"); 
						} 
					}
				});
				
				// Dialog Link
				$('#dialog_link').click(function(){
					$('#dialog').dialog('open');
					return false;
				});

				
				
				// Slider
				$('#slider').slider({
					range: true,
					values: [17, 67]
				});
				
				// Progressbar
				$("#progressbar").progressbar({
					value: 20 
				});
				
				//hover states on the static widgets
				$('#dialog_link, ul#icons li').hover(
					function() { $(this).addClass('ui-state-hover'); }, 
					function() { $(this).removeClass('ui-state-hover'); }
				);
				
			});
		</script>
</head>
  <body>  
  
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>